#!/bin/bash
# Copyright 2018-2020 Marco Fontani <MFONTANI@cpan.org>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# README: colorz
#
# Displays:
# - all 256 ANSI colors your terminal hopefully supports
# - the "base" foreground and background colors
# - a truecolor "rainbow", useful to see if your terminal supports it.
#
# Provide one color number to see it used in the background color.
#
# Usage:
#
# - `colorz`
# - `colorz 22`
# - `colorz 22 23`

if [[ -n "$1" ]]; then
    if [[ -n "$2" ]]; then
        perl -e'
        for(@ARGV) {
            s/\Acolor//;
            my $l = 5 - length "$_";
            printf  "\x1b[38;5;%umcolor%u\x1b[0m\n", $_, $_;
        }
        ' "$@"
        exit 0
    else
        perl -e'
        for(@ARGV) {
            s/\Acolor//;
            my $l = 5 - length "$_";
            printf  "\x1b[48;5;%umcolor%u\x1b[0m", $_, $_;
        }
        ' "$@"
        exit 0
    fi
fi
perl -e'for(0..255) { my $l = 5 - length "$_"; printf( "\x1b[38;5;%umcolor%u%s", $_, $_, " "x$l,); print "\n" if $_ % 10 == 9; } print "\n";'
perl -e'for(30..37) { print " " if $_ != 30; printf "\x1b[%dm%-2s\x1b[0m", $_, $_ }; print "\n"'
perl -e'for(40..47) { print " " if $_ != 40; printf "\x1b[%dm%-2s\x1b[0m", $_, $_ }; print "\n"'
awk 'BEGIN{
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
    for (colnum = 0; colnum<77; colnum++) {
        r = 255-(colnum*255/76);
        g = (colnum*510/76);
        b = (colnum*255/76);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
}'
