#!/bin/bash
# Copyright 2018-2020 Marco Fontani <MFONTANI@cpan.org>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# README: evenodd
#
# Colorizes STDIN lines (even and odd), with a given optional color for the
# background color to be used.
#
# Usage:
#
# - `foo | evenodd`
# - `foo | evenodd 42`

color=233
if [[ "$1" != "" ]]; then
    if [[ "x$1" == "x--help" ]]; then
        >&2 cat <<END_USAGE
Usage: $(basename "$0") [COLOR]

Colorizes STDIN lines (even and odd).
Even lines have a reset background color.
Odd lines have a given background color, default $color.
You can specify the COLOR to use instead of $color.
END_USAGE
        exit 0
    fi
    color="$1"
    shift
fi
if [[ "$1" != "" ]]; then
    >&2 echo "Too many arguments. Only one optional argument, a color number for the background."
    exit 1
fi
reset="$( printf "\x1b[0m" )"
odd="$( printf "\x1b[48;5;%sm" "$color" )"

flag=0
while IFS= read -r line; do
    if [[ "$flag" == "0" ]]; then
        printf '%s\n' "$line"
        flag=1
    else
        echo "$odd$(printf "%s" "$line" | sed -e "s/\x1b\[0m/\x1b[0;48;5;${color}m/g")$reset"
        flag=0
    fi
done
