#!/bin/bash
# Copyright 2018-2020 Marco Fontani <MFONTANI@cpan.org>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# README: gz-to-zst
#
# Convert given `*.gz` files into `*.zst` files (at `-9`), and show statistics
# for space saved by the conversion
#
# Usage:
# - `gz-to-zst foo.gz`
# - `gz-to-zst *.gz`

if [[ -z "$1" ]]; then
    >&2 echo 'Usage: gz-to-zst FILE [FILE, ]'
    exit 1
fi

for file in "$@"; do
    if [[ ! -f "$file" ]]; then
        >&2 echo "File '$file' does not exist"
        continue
    fi
    if ! [[ $file =~ \.gz$ ]]; then
        >&2 echo "File '$file' does not seem to end in .gz"
        continue
    fi
    before=$(stat --printf='%s' "$file")
    base=${file%.gz}
    gunzip --quiet "$file"
    zstd --quiet --rm -9 "$base"
    after=$(stat --printf='%s' "$base.zst")
    >&2 echo "$file - $before -> $after = $((before - after)) saved"
done
